added the ability to change the center of the camera focus
dns-technologies/mlkit_scanner pull request #3
Opened 2022-07-12 07:06 UTC by SkrejetCepey

Добавил возможность смещать фокус камеры.

Теперь по умолчанию камера фокусируется по середине визора.

+ фикс уголков, теперь они всегда 13px (согласно дизайн системе).

2022-07-18 03:03 UTC, jagrdev requested changes

2022-07-18 03:03 UTC, jagrdev commented on android/src/main/kotlin/com/dns_technologies/mlkit_scanner/CenterFocusView.kt
> +        val (l, r) = if (horizontalMargin > 0) Pair(0, horizontalMargin.absoluteValue) else Pair(0, horizontalMargin.absoluteValue)
```suggestion
        val (l, r) = if (horizontalMargin > 0) Pair(horizontalMargin.absoluteValue, 0) else Pair(0, horizontalMargin.absoluteValue)
```

2022-07-18 03:03 UTC, jagrdev commented on android/src/main/kotlin/com/dns_technologies/mlkit_scanner/ScannerOverlay.kt
> +        val radius = 13
Почему хардкод?

2022-07-18 03:59 UTC, SkrejetCepey commented on android/src/main/kotlin/com/dns_technologies/mlkit_scanner/CenterFocusView.kt
> +        val (l, r) = if (horizontalMargin > 0) Pair(0, horizontalMargin.absoluteValue) else Pair(0, horizontalMargin.absoluteValue)
Забавно, это многое объясняет

2022-07-18 04:00 UTC, SkrejetCepey commented on android/src/main/kotlin/com/dns_technologies/mlkit_scanner/ScannerOverlay.kt
> +        val radius = 13
Надо вывернуть на уровень флаттера, займусь этим в том числе.

2022-07-21 05:36 UTC, SkrejetCepey commented
замочек на платформах сейчас немного по разному работает. На андройде кажется более неприятно так как я там центрирую с помощью маргинов.  Поищу другой способ

2022-07-21 05:41 UTC, SkrejetCepey commented
> замочек на платформах сейчас немного по разному работает. На андройде кажется более неприятно так как я там центрирую с помощью маргинов.  Поищу другой способ

перепишу на транслейшен

2022-07-25 02:02 UTC, SkrejetCepey commented
- [ ] Пофиксить позицию откуда вылетает замочек на андройде :/

2022-08-01 03:12 UTC, skrjt commented
На андройде были небольшие приколы с транслейтами иконки замка, поэтому он сделан немного по другому (сам немного кринжую).
В чем соль. Когда я подвигал иконку замка (транслейты или просто через кастомный транзишин) почему-то был баг, когда происходит действие снятия фокуса (тап после лока автофокуса) замок прыгал на свою базовую позицию (хотя анимация предполагает просто изменение прозрачности). Я долго пытался понять что же там не так.
Забавно то, что все работает нормально, если не пользоваться изменением позиции значка (а например, просто смещать позицию в оффсетах).
Переделывать то, что уже сделано на оффсеты не стал, так как фокус-кружок вроде нормально работает с транслейтами.
Возможно, что была проблема в том, что замок улетал за карту (по позишн, это я не дебажил).
Придется немного подучится в эти факинг анимейшенс и сделать получше.

2022-08-01 07:03 UTC, skrjt commented on android/src/main/kotlin/com/dns_technologies/mlkit_scanner/CenterFocusView.kt
> +        val deltaX = lock.height * 0.8F - lock.x
lock.width

2022-08-02 00:02 UTC, grebennikovlmax approved these changes

2022-08-02 00:04 UTC, merged