Initial parameters for scanner
dns-technologies/mlkit_scanner pull request #32
Opened 2023-04-17 07:26 UTC by skrjt

2023-04-19 00:40 UTC, 8symbols requested changes

2023-04-19 00:40 UTC, 8symbols commented on lib/platform/ml_kit_channel.dart
> +  Future<void> initCameraPreview({double? initialZoom, CropRect? initialCropRect, IosCamera? initialCamera}) {
Передавать отдельные объекты с аргументами для iOS и Android

2023-04-19 00:40 UTC, 8symbols commented on ios/Classes/CameraPreview.swift
> +        if (initialZoom != nil) {
```suggestion
        if let initialZoom = initialZoom  {
```

2023-04-19 00:40 UTC, 8symbols commented on ios/Classes/CameraPreview.swift
> +            try internalSetZoom(initialZoom!)
```suggestion
            try internalSetZoom(initialZoom)
```

2023-04-19 00:40 UTC, 8symbols commented on ios/Classes/CameraPreview.swift
> +            try internalSetZoom(initialZoom!)
```suggestion
            try setZoom(initialZoom!)
```

2023-04-19 00:40 UTC, 8symbols commented on ios/Classes/CameraPreview.swift
> +        guard let camera = camera else {
Остальные проверки в setZoom были просто так? Точно будет работать

2023-04-19 00:40 UTC, 8symbols commented on ios/Classes/MlKit/CameraData.swift
> +        guard let type = AVCaptureDevice.DeviceType.fromCode(arguments!["type"] as! Int),
Если не скастуется, вылетит?

2023-04-19 00:40 UTC, 8symbols commented on ios/Classes/SwiftMlkitScannerPlugin.swift
> +            return;
```suggestion
            return
```

2023-04-19 00:40 UTC, 8symbols commented on ios/Classes/SwiftMlkitScannerPlugin.swift
> +        var deviceTypes: [AVCaptureDevice.DeviceType] = [
Убрать из CameraPreview, вынести в отдельный класс

2023-04-19 00:40 UTC, 8symbols commented on lib/models/ios_camera.dart
> +  Map<String, dynamic> toJson() => {
В отдельную модель

2023-04-19 00:40 UTC, 8symbols commented on lib/helpers/ios_helper.dart
> +class IosHelper {
Не нужен

2023-04-19 00:40 UTC, 8symbols commented on lib/models/ios_camera_position.dart
> +  static int toCode(IosCameraPosition position) => _positionToCode[position]!;
```suggestion
```

2023-04-19 00:40 UTC, 8symbols commented on lib/models/ios_camera_type.dart
> +  static int toCode(IosCameraType type) => _typeToCode[type]!;
```suggestion
```

2023-04-19 00:40 UTC, 8symbols commented on lib/platform/ml_kit_channel.dart
> +  final StreamController<String> _scanResultStreamController = StreamController<String>.broadcast();
Форматирование для 80

2023-04-19 00:40 UTC, 8symbols commented on lib/widgets/camera_preview.dart
> -      await _channel.initCameraPreview();
Вернуть

2023-04-20 00:30 UTC, jagrdev requested changes

2023-04-20 00:30 UTC, jagrdev commented on android/src/main/kotlin/com/dns_technologies/mlkit_scanner/models/InitialScannerParameters.kt
> +data class InitialScannerParameters(
`Initial` ИМХЛО лишнее. На использование это никаких ограничений не накладывает. 
```suggestion
data class ScannerParameters(
```
Для подобного смысла лучше именовать переменные или поля:
`val initialParams` и т.д.

2023-04-20 00:30 UTC, jagrdev commented on android/src/main/kotlin/com/dns_technologies/mlkit_scanner/models/InitialScannerParameters.kt
> +    val initialZoom: Double? = null,
`Initial` по отношению к данным класса является внешним контекстом. То есть он никак не используется внутри класса. Стоит назвать:
```suggestion
    val zoom: Double? = null,
    val cropArea: RecognizeVisorCropRect? = null,
```

2023-04-20 00:30 UTC, jagrdev commented on ios/Classes/CameraPreview.swift
> +    private func internalSetZoom(_ value: Double) throws {
Какой смысл вкладывается в internal?
```suggestion
    private func setZoom(_ value: Double) throws {
```

2023-04-20 00:30 UTC, jagrdev commented on ios/Classes/MlKit/InitialScannerParameters.swift
> +struct InitialScannerParameters {
```suggestion
struct ScannerParameters {
```

2023-04-20 00:30 UTC, jagrdev commented on ios/Classes/SwiftMlkitScannerPlugin.swift
> +            internalSetCropArea(rect: initialScannerParameters!.initialCropRect!)
```suggestion
            setCropArea(rect: initialScannerParameters!.initialCropRect!)
```

2023-04-20 02:34 UTC, 8symbols requested changes

2023-04-20 02:34 UTC, 8symbols commented on ios/Classes/SwiftMlkitScannerPlugin.swift
> +        if (isAlreadyInitialized == true) {
```suggestion
        if (isAlreadyInitialized) {
```

2023-04-20 02:34 UTC, 8symbols commented on ios/Classes/SwiftMlkitScannerPlugin.swift
> +        if (initialScannerParameters?.initialCropRect != nil) {
```suggestion
        if let initialCropRect = initialScannerParameters?.initialCropRect {
```

2023-04-20 02:34 UTC, 8symbols commented on ios/Classes/MlKit/CameraData.swift
> +        if (arguments == nil) {
```suggestion
        guard let arguments = arguments else {
```

2023-04-20 02:34 UTC, 8symbols commented on ios/Classes/MlKit/InitialScannerParameters.swift
> +        if (arguments == nil) {
```suggestion
```

2023-04-20 02:34 UTC, 8symbols commented on ios/Classes/MlKit/InitialScannerParameters.swift
> +        guard let initialZoom = arguments!["initialZoom"] as? Double?,
```suggestion
        guard let arguments = arguments, initialZoom = arguments!["initialZoom"] as? Double?,
```

2023-04-20 02:34 UTC, 8symbols commented on ios/Classes/MlKit/CameraData.swift
> +    init?(arguments: Dictionary<String, Any?>?) {
```suggestion
    init(arguments: Dictionary<String, Any?>) {
```

2023-04-20 02:34 UTC, 8symbols commented on ios/Classes/CameraUtil.swift
> +class CameraUtil {
```suggestion
class CameraUtils {
```

2023-04-20 02:34 UTC, 8symbols commented on ios/Classes/MlKit/CameraData.swift
> +struct CameraData {
Использовать везде или отказаться

2023-04-20 02:34 UTC, 8symbols commented on lib/models/empty_initial_arguments.dart
> +///
```suggestion
```

2023-04-20 02:34 UTC, 8symbols commented on lib/models/empty_initial_arguments.dart
> +///
```suggestion
```

2023-04-20 02:34 UTC, 8symbols commented on lib/models/empty_initial_arguments.dart
> +class EmptyInitialArguments extends InitialArguments {
Удалить

2023-04-20 02:34 UTC, 8symbols commented on lib/models/initial_arguments.dart
> +  Map<String, dynamic> toJson();
Неочевидно, что в потомках надо прописать еще родительские поля

2023-04-20 02:34 UTC, 8symbols commented on lib/utils/mlkit_utils.dart
> +class MlkitUtils {
```suggestion
class MLKitUtils {
```

2023-04-20 05:10 UTC, 8symbols requested changes

2023-04-20 05:10 UTC, 8symbols commented on android/src/main/kotlin/com/dns_technologies/mlkit_scanner/CameraViewScannerCamera.kt
> +        if (cameraOptions?.isZoomSupported != false) {
```suggestion
        if (cameraOptions?.isZoomSupported ?: true) {
```

2023-04-20 05:10 UTC, 8symbols commented on android/src/main/kotlin/com/dns_technologies/mlkit_scanner/CameraViewScannerCamera.kt
> +        if (cameraOptions?.isZoomSupported != false) {
Нужен комментарий с пояснением, почему до инициализации игнорируется проверка

2023-04-20 05:10 UTC, 8symbols commented on android/src/main/kotlin/com/dns_technologies/mlkit_scanner/models/ScannerParameters.kt
> +        (map["initialZoom"] as Double?),
```suggestion
        map["initialZoom"] as Double?,
```

2023-04-20 05:10 UTC, 8symbols commented on ios/Classes/SwiftMlkitScannerPlugin.swift
При установке камеры тоже тогда надо перейти на использование `CameraData`

2023-04-20 06:01 UTC, 8symbols approved these changes

2023-04-21 05:59 UTC, jagrdev approved these changes

2023-04-24 00:42 UTC, merged