MPK-2851
dns-technologies/mlkit_scanner pull request #40
Opened 2023-08-09 06:39 UTC by skrjt

Synchronized scanning throttling logic between platforms

2023-08-13 23:28 UTC, 8symbols requested changes

2023-08-13 23:28 UTC, 8symbols commented on ios/Classes/MlKit/MlkitBarcodeScanner.swift
> +        isRecognitionInProgress = false
Если `recognizeBarcodeOnFrame` выкинет ошибку, `isRecognitionInProgress` не сбросится. Можно использовать [defer](https://www.hackingwithswift.com/new-syntax-swift-2-defer)

2023-08-13 23:28 UTC, 8symbols commented on ios/Classes/MlKit/MlkitBarcodeScanner.swift
> +    private func canRecognize() -> Bool {
Уместнее был бы геттер

2023-08-15 01:22 UTC, 8symbols approved these changes

2023-08-15 05:49 UTC, desperationbtw approved these changes

2023-08-15 07:23 UTC, skrjt commented
- [ ] merge after successful testing

2023-09-01 06:27 UTC, jagrdev approved these changes

2023-09-05 02:59 UTC, merged